[package]
name = "good-os-framework"
version = "0.5.2"
edition = "2021"
repository = "https://github.com/zzjrabbit/good-os-framework"
description = "A simple operating system framework for framekernel written in Rust"
license = "MIT/Apache-2.0"
keywords = ["os", "rust", "framework", "framekernel" ,"no_std"]

[features]
smp = []

[dependencies]
limine = "0.2.0"
x86_64 = "0.15.1"
acpi = "5.0.0"
spin = "0.9.8"
x2apic = "0.4.3"
bitflags = "2.6.0"
uart_16550 = "0.3.0"
pc-keyboard = "0.7.0"
bit_field = "0.10.2"
good_memory_allocator = "0.1.7"
vte = "0.13.0"
colorz = "1.1.2"
xhci = "0.9.2"
talc = "4.4.1"

[dependencies.time]
version = "0.3.36"
default-features = false

[dependencies.os-terminal]
version = "0.3.7"
features = ["truetype"]
# path = "../os-terminal"

[dependencies.pci]
package = "pci-for-framework"
version = "0.0.1"

[dependencies.log]
version = "0.4.22"
default-features = false

[dependencies.crossbeam-queue]
version = "0.3.11"
features = ["alloc"]
default-features = false

[dependencies.noto-sans-mono-bitmap]
version = "0.3.0"
features = ["bold", "size_20", "unicode-basic-latin"]
default-features = false

[dependencies.conquer-once]
version = "0.4.0"
default-features = false

[dependencies.object]
version = "0.36.1"
features = ["read_core", "elf", "unaligned"]
default-features = false
